# Generated by Django 4.1.3 on 2022-11-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_author'),
        ('comments', '0002_alter_comment_author'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
